version: "2"

services:
  asciidoctor:
    image: asciidoctor/docker-asciidoctor
    volumes:
      - ../:/documents
      - ../../open-simulation-interface:/open-simulation-interface
      - ../../osi-sensor-model-packaging:/osi-sensor-model-packaging
    entrypoint: asciidoctor -a local=true --failure-level WARN -r asciidoctor-kroki -a mathjax -r asciidoctor-bibtex --trace content/index.adoc -o local_build_tools/HTML_content_local_build.html