name: Remote Tagging

on:
  repository_dispatch:
    types: [update-tag]
    
jobs:
  submodule:
    name: Create tag
    runs-on: Ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: repo
      - name: Update with tag
        run: |
          cd repo
          git tag ${{ github.event.client_payload.tag }}
          git push --atomic origin master ${{ github.event.client_payload.tag }}
         
